### ISSUE TITLE
Enhancement: Cosmos DB Databases and Containers by adding Throughput

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Ensono/amido.github.io#12]
Now https://github.com/terraform-providers/terraform-provider-azurerm/pull/5203 has been merged, after a release we should add throughput to CosmosDB Databases instead of collections. The PR supports container and DB provisioned throughput

Question for thought: If 400 is the minimum and each container needs 100 RU minimum then terraform could try to resize to an invalid value. 🤔 
Maybe we should enforce an approach of _always_ using Terraform to create new Containers and Databases.

**Comment by estherthetesteramido** [comment]
@dnitsch what additional enhancements may we want to add to this?
