### ISSUE TITLE
Make stacks-packages a public project

### ISSUE THREAD

**Issue by chris31389** [Ensono/amido.github.io#153]
**Is your feature request related to a problem? Please describe.**
`stacks-packages` is currently a private project, when there is no requirement to be a private project.

**Describe the solution you'd like**
Any solution requires new repositories, so that we can remove the history and any secret information that we don't want the community to get hold off.

Two options are.
1) Create a new repository and copy the code over as it is.
2) Create a repository per package that is generated. **[Preferred]**

Any new repository will require:
- setup security and access permissions (techops), 
- pipeline access, 
- update all pipelines configuration, 
- move shared files/steps etc

**Additional context**
It may make sense to do this in steps, with the first step to re-organise the folder structure so each project has its own folder, ready to seperate into its own repo's.

**Comment by chris31389** [comment]
An added bonus of this is that we might be able to make use of the public build agents in azure:

![image](https://user-images.githubusercontent.com/5216375/99385124-6d76bb00-28c8-11eb-8f02-9b12cf73902f.png)

**Comment by ElvenSpellmaker** [comment]
The pipelines are currently in a private organisation which is why they use the private agents. I'm not sure how much we want to expose of the actual project side of things.
