### ISSUE TITLE
pactnet causes issue with long path name on Windows

### ISSUE THREAD

**Issue by chris31389** [Ensono/amido.github.io#164]
**Repository the bug was found in**

stacks-dotnet

**Describe the bug**

pactnet has a *long* path and is close to the 256 limit for windows folder paths.  If you have a long company name or project name, and with a longer than normal repo name, it will cause issues when building using visual studio 2019.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4846,5): warning MSB3026: Could not copy "C:\Users\ChrisButler\.nuget\packages\pactnet.windows\2.4.6\tools\pact-win32\lib\vendor\ruby\2.2.0\gems\pact-provider-verifier-1.23.1\lib\pact\provider_verifier\provider_states\remove_provider_states_header_middleware.rb" to "bin\Debug\netcoreapp3.1\pact-win32\lib\vendor\ruby\2.2.0\gems\pact-provider-verifier-1.23.1\lib\pact\provider_verifier\provider_states\remove_provider_states_header_middleware.rb". Beginning retry 1 in 1000ms. Could not find a part of the path 'bin\Debug\netcoreapp3.1\pact-win32\lib\vendor\ruby\2.2.0\gems\pact-provider-verifier-1.23.1\lib\pact\provider_verifier\provider_states\remove_provider_states_header_middleware.rb'.

**To Reproduce**

clone the repository to a path with a long name.  e.g. `git clone C:\my-very-long\looking-path-name\Amido.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.repo`

build using visual studio

**Expected behaviour**

A build should be successful

**Platform (please complete the following information):**
PC

**Additional context**
Visual Studio 2019 (16.8.2)
Windows 10

One fix is to suggest this:

https://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html

**Comment by ElvenSpellmaker** [comment]
Yeah we knew about this a while back, we'd gru to move the potjects close to the root of the repo.

Alternatives could be using Docker or WSL for running builds.

**Comment by chris31389** [comment]
Is it possible to put something in the docs maybe in an FAQ section?
