### ISSUE TITLE
Enhancement: Step "Use .NET Core SDK 3.1.x" should be optional

### ISSUE THREAD

**Issue by guibirow** [Ensono/amido.github.io#27]
**Feature, tool or process you are suggesting improvement for:**

Dotnet pipelines has a step called "Step "Use .NET Core SDK 3.1.x" which should be optional.
This step was introduced to switch the tooling version when .net core 3.1 was still in preview, nowadays it is already installed in the box and should be used only when we want to switch sdk version. 

This step currently 1 and a half minute to the build duration.

Warning from pipeline:
> Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.0 and 3.1) SDK/Runtime along with 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 

**How you suggest to improve it:**

Make the step optional and only run if a value is provided in the pipeline

**Comment by ElvenSpellmaker** [comment]
FWIW I think it's best to always pin else you can end up with nasty surprises when they eventually upgrade to a newer version.

This happened to us with Helm for example, when the agents changed from Helm 2 to 3 it broke our nginx-ingress deploy.

Maybe, as another thought this could be changed to check if the supplied .NET is not installed and install it if it isn't? If no .NET version is supplied, check if the default (3.1 for example) is installed and install if not. Just some thoughts.

**Comment by guibirow** [comment]
Check if .Net is installed should also help to speedup the process.

Microsoft keep all LTS releases in the build image, it shouldn't be a problem, unless we plan to keep supporting versions that are out of support, that is where this step would be required.
